apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goodbye-svc
  name: goodbye-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goodbye-svc
  template:
    metadata:
      labels:
        app: goodbye-svc
    spec:
      containers:
      - image: 962675440091.dkr.ecr.us-west-2.amazonaws.com/goodbye@sha256:dc4b213f4318f390bff7f1a0bab025d5f8b7109f880c46cc2dbb073743d15780
        name: goodbye-svc
        ports:
          - containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080